DOCS_SLUG_TO_TEMPLATE = {
    'what-is-graphicsh': 'docs/getting-started/what-is-graphicsh.html',
    'what-is-graphics': 'docs/getting-started/what-is-graphicsh.html',
    'where-to-run': 'docs/getting-started/where-to-run.html',
    'hello-graphics': 'docs/getting-started/hello-graphics.html',
    'graphics-initialization': 'docs/initialization/graphics-initialization.html',
    'line-and-movement': 'docs/drawing/line-and-movement.html',
    'circle': 'docs/drawing/circle.html',
    'rectangle': 'docs/drawing/rectangle.html',
    'bar': 'docs/drawing/bar.html',
    'bar3d': 'docs/drawing/bar3d.html',
    'arc': 'docs/drawing/arc.html',
    'ellipse': 'docs/drawing/ellipse.html',
    'pieslice': 'docs/drawing/pieslice.html',
    'sector': 'docs/drawing/sector.html',
    'polygons-and-fill': 'docs/polygons/polygons-and-fill.html',
    'colors-and-palette': 'docs/colors/colors-and-palette.html',
    'fill-and-patterns': 'docs/fill/fill-and-patterns.html',
    'viewport-and-screen': 'docs/viewport/viewport-and-screen.html',
    'text-and-fonts': 'docs/text/text-and-fonts.html',
    'image-handling': 'docs/image/image-handling.html',
    'drivers-and-modes': 'docs/drivers/drivers-and-modes.html',
    'advanced-functions': 'docs/advanced/advanced-functions.html',
    'error-codes': 'docs/errors/error-codes.html',
}

DEFAULT_DOCS_SLUG = 'what-is-graphicsh'
DOCS_SITE_TITLE = 'graphics.h online compiler docs'

DOCS_CANONICAL_SLUGS = {
    'what-is-graphics': 'what-is-graphicsh',
}

DOCS_SLUG_TO_TITLE = {
    'what-is-graphicsh': 'What is graphics.h',
    'what-is-graphics': 'What is graphics.h',
    'where-to-run': 'Where to Run graphics.h',
    'hello-graphics': 'Hello Graphics Program',
    'graphics-initialization': 'Graphics Initialization',
    'line-and-movement': 'Line and Cursor Movement',
    'circle': 'circle()',
    'rectangle': 'rectangle()',
    'bar': 'bar()',
    'bar3d': 'bar3d()',
    'arc': 'arc()',
    'ellipse': 'ellipse()',
    'pieslice': 'pieslice()',
    'sector': 'sector()',
    'polygons-and-fill': 'Polygons and Fill',
    'colors-and-palette': 'Colors and Palette',
    'fill-and-patterns': 'Fill and Patterns',
    'viewport-and-screen': 'Viewport and Screen',
    'text-and-fonts': 'Text and Fonts',
    'image-handling': 'Image and Pixel Operations',
    'drivers-and-modes': 'Drivers and Modes',
    'advanced-functions': 'Advanced Functions',
    'error-codes': 'Error Codes',
}

DOCS_SLUG_TO_DESCRIPTION = {
    'what-is-graphicsh': 'Learn what graphics.h is, why it is still taught, and which modern alternatives like SDL and SFML are better for real-world development.',
    'what-is-graphics': 'Learn what graphics.h is, why it is still taught, and which modern alternatives like SDL and SFML are better for real-world development.',
    'where-to-run': 'Compare the best ways to run graphics.h programs: online compiler, VS Code extension, Turbo C with DOSBox, and Ubuntu setup options.',
    'hello-graphics': 'Build and run your first graphics.h hello graphics program with step-by-step explanation, code sample, and DOS output preview.',
    'graphics-initialization': 'Understand graphics.h initialization using initgraph, detectgraph, graphresult, grapherrormsg, closegraph, and restorecrtmode.',
    'line-and-movement': 'Learn line drawing and cursor movement concepts in graphics.h with beginner-friendly examples.',
    'circle': 'Explore graphics.h circle() function syntax, parameters, and usage examples.',
    'rectangle': 'Explore graphics.h rectangle() function syntax, parameters, and usage examples.',
    'bar': 'Explore graphics.h bar() function syntax, parameters, and usage examples.',
    'bar3d': 'Explore graphics.h bar3d() function syntax, parameters, and usage examples.',
    'arc': 'Explore graphics.h arc() function syntax, parameters, and usage examples.',
    'ellipse': 'Explore graphics.h ellipse() function syntax, parameters, and usage examples.',
    'pieslice': 'Explore graphics.h pieslice() function syntax, parameters, and usage examples.',
    'sector': 'Explore graphics.h sector() function syntax, parameters, and usage examples.',
    'polygons-and-fill': 'Learn polygon drawing and fill operations in graphics.h with practical examples.',
    'colors-and-palette': 'Understand graphics.h color constants, palette usage, and fill color behavior.',
    'fill-and-patterns': 'Learn fill styles and patterns in graphics.h for area shading and visual effects.',
    'viewport-and-screen': 'Understand graphics.h viewport, coordinate clipping, and screen handling basics.',
    'text-and-fonts': 'Learn text rendering functions and font styling in graphics.h.',
    'image-handling': 'Learn graphics.h image and pixel operations including putpixel, getimage, and putimage.',
    'drivers-and-modes': 'Understand graphics.h drivers, graphics modes, and compatibility concerns.',
    'advanced-functions': 'Explore advanced graphics.h functions and practical usage tips.',
    'error-codes': 'Learn graphics.h error codes and debugging techniques for initialization and drawing issues.',
}
